config/routes.rb
Rails.application.routes.draw do
  
  root 'members#index'
  resources :members

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :member
  
  # show friends in reverse chronological order
  default_scope -> { order(created_at: :desc) }
  
  validates :member_id, presence: true
  validates :friend_id, presence: true
  
end

app/models/heading.rb
class Heading < ApplicationRecord
  belongs_to :member
  
  # show headings in reverse chronological order
  default_scope -> { order(created_at: :desc) }
  
  validates :member_id, presence: true
  validates :content, presence: true
  
  # partial match search excluding current member
  def self.search(args = {})
    s_text = args[:search_text]
    member = args[:member]
    if !s_text.blank? && member.present?
      partial_match = "%#{s_text.downcase}%"
      # todo: pagination
      # investigate what Arel is about...
      where("LOWER(content) LIKE ? AND member_id != ?", partial_match, member.id)
    end
  end
  
end

app/models/member.rb
class Member < ApplicationRecord
  # removing child heading and friend records when a member is deleted.
  has_many :headings, dependent: :destroy
  has_many :friends, dependent: :destroy
  
  validates :name, presence: true
  validates :pws_full_url, presence: true
  
  def self.find_by_ids(*ids)
    if ids.any?
      where(id: ids)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
      render html: "hello rails!"
  end
    
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/headings_controller.rb
class HeadingsController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  def index
    @members = Member.all
  end
  
  # disabled for now
  def new
    @member = Member.new
  end

  def show
    @member = Member.find(params[:id])
    @headings = @member.headings

    # get friends, if any.
    friend_ids = @member.friends.pluck(:friend_id)
    if friend_ids.any?
      # get member objects for the friends
      @friends_data = Member.find_by_ids(friend_ids)
    end
    
    # search experts, if any.
    # Notes: per discussion with Dustin, Members, who are not friends, do not need a common friend to be qualified for search results.  
    # e.g. Alan -> Claudia ("Dog breeding in Ukraine") instead of Alan -> Bart -> Claudia ("Dog breeding in Ukraine").
    search_experts({ :search_text => params[:search_text],
                     :friend_ids => friend_ids })
                     
  end

  # todo - not working yet...
  def create
    @member = Member.new(member_params)
    # todo - need shorten url gem or web service
    @member.pws_short_url = "todo"
    
    if @member.save
      # todo: fetch headings, if any, from personal website and save them to MemberHeading
      # show all members
      redirect_to :action => 'index'
    else
      render 'new'
    end
  end
  
  private
  
    def member_params
      params.require(:member).permit(:name, :pws_full_url)
    end
    
    def search_experts(args = {})
      s_text = args[:search_text]
      friend_ids = args[:friend_ids]
      @experts = []
      if s_text.present?
        search_args = { :search_text => s_text, :member => @member}
        heading_results = Heading.search(search_args)
        
        if heading_results.any?
          # process resuts
          heading_results.each do |hr|
            puts "hr:" + hr.to_s
            hr_member_id = hr.member.id
            next if friend_ids.any? && friend_ids.include?(hr_member_id)
            @experts << { :member_id => hr_member_id, :name => hr.member.name, :heading => hr.content}
          end
        end
        
        @search_no_results_msg = "No results found" if @experts.blank?

      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/headings_helper.rb
module HeadingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/friends/_expert.html.erb
<ul class="experts">
  <% if @experts.any? %>
    <% @experts.each do |e| %>
      <li id="expert-<%= e[:member_id] %>">
        <span class="expert"><%= @member.name + " -> " + e[:name] + " (\"" + e[:heading] + "\")" %></span>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/friends/_friend_data.html.erb
<ul class="friends">
  <% @friends_data.each do |fd| %>
    <li id="friend-<%= fd.id %>">
      <span class="friend"><%= link_to fd.name, member_path(fd) %></span>
    </li>
  <% end %>
</ul>

app/views/headings/_heading.html.erb
<li id="heading-<%= heading.id %>">
  <span class="content"><%= heading.content %></span>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EwChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/index.html.erb
<h1>All members</h1>

<% @members.each do |member| %>
  Name: <%= link_to member.name, member_path(member) %><br/>
  Website Short URL: <%= member.pws_short_url %><br/>
  # of friends: <%= member.friends.count %><br/><br/>
<% end %>

app/views/members/new.html.erb
<h1>New Member</h1>

<div>
  <%= form_for(@member) do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %>
    <br/>
    <%= f.label "Personal Website URL" %>:
    <%= f.text_field :pws_full_url %>
    <br/><br/><br/>
    <%= f.submit "Create Memeber" %>
  <% end %>
</div>

app/views/members/show.html.erb
<h1><%= @member.name %> Profile </h1>
Website URL: <%= @member.pws_full_url %><br/>
Short URL: <%= @member.pws_short_url %><br/>

<h2>Headings</h2>
<% if @headings.any? %>
    <ul class="headings">
        <%= render @headings %>
    </ul>
<% else %>
    No headings found
<% end %>

<h2>Friends</h2>
<% if @friends_data.present? %>
    <ul class="friends">
        <%= render 'friends/friend_data.html.erb' %>
    </ul>
<% else %>
    You don't have any friends yet...
<% end %>

<h2>Find Experts</h2>
<%= form_tag(member_path, :method => "get") do %>
    <%= text_field_tag :search_text, params[:search_text], :value => '' %>
    <%= submit_tag "Search" %>
<% end %>


<h2>Search Results</h2>
<% if @experts.present? %>
    <ul class="experts">
        <%= render 'friends/expert.html.erb' %>
    </ul>
<% end %>
<%= @search_no_results_msg %>

<br/><br/><br/><%= link_to "Back to All Members", root_path %>